### ISSUE TITLE
Problems compiling for Linux 

### ISSUE THREAD

**Issue by AutumnCorpse1** [Teledyne-MV/Spinnaker-Examples#1]
I am having trouble compiling an example program C++ using the example files for a Linux system, but I can compile on a Windows system using the Windows libraries. Could you provide an example code to compile an example using the Linux libraries?

**Comment by Wangh257** [comment]
I'm encountering an issue during the testing of a process called 'RAWToProcess', where the input raw image and the output raw image are completely different from each other. I suspect the issue might be with the tempImage->GetData() method. Could there be a problem with how tempImage->GetData() is retrieving the image data, leading to such a discrepancy in the output?

**Comment by WilliamRGallego** [comment]
hi Wangh257, to troubleshoot your issue, I would recommend opening a ticket by going to flir.custhelp.com, then clicking on the "ask a question" box to proceed forward.  I would advise including details such as all custom values you used, as well as the camera model you are testing with.

**Comment by aliseba** [comment]
I have encountered an issue during the using of a process called 'CameraToPCTime', where the imageTimestamp_converted is around  200ms less than the right and real timestamp isued by an other method. When I search the problem I find that my 200ms is exactly the difference between the timestampLatchValue and the ChunkData Timestamp. ByTheWay  there is technical note from FLIR that define that both timestamp are equal ? if is equal why we use the both to extract and to add ? my Camera is BFS-PGE-161s
